# Generated by Django 2.0.4 on 2018-05-01 14:18

from django.db import migrations


def create_garage(apps, schema_editor):
    # Мы здесь не можем импортировать модели из модуля моделей
    # Поэтому, получаем через .get_model()
    Car = apps.get_model('myapp', 'Car')
    Garage = apps.get_model('myapp', 'Garage')
    all_cars = Car.objects.all()
    number_of_cars = len(all_cars)
    # Создаем новый гараж с вместимостью, которая совпадает
    # с количеством машин, которые у нас есть в базе 
    new_garage = Garage.objects.create(
        name='new garage', capacity=number_of_cars)


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_garage'),
    ]

    operations = [
        migrations.RunPython(create_garage),
    ]
