# Generated by Django 2.0.4 on 2018-05-01 14:24

from django.db import migrations


def put_cars_into_garage(apps, schema_editor):
    # Sorry, my fault. Here was a stupid migration
    # Refer to migration: 0007_auto_20180501_1433.py
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20180501_1418'),
    ]

    operations = [
        migrations.RunPython(put_cars_into_garage),
    ]
