# Generated by Django 2.0.4 on 2018-05-01 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20180501_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='garage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', related_query_name='car', to='myapp.Garage'),
        ),
    ]
