# Generated by Django 2.0.4 on 2018-05-01 14:33

from django.db import migrations


def put_cars_into_garage(apps, schema_editor):
    Car = apps.get_model('myapp', 'Car')
    Garage = apps.get_model('myapp', 'Garage')
    garage = Garage.objects.all().first()
    all_cars = Car.objects.all()
    for car in all_cars:
        car.garage = garage
        car.save()

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_car_garage'),
    ]

    operations = [
        migrations.RunPython(put_cars_into_garage),
    ]
