# Generated by Django 2.0.4 on 2018-05-01 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20180501_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='garage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', related_query_name='car', to='myapp.Garage'),
        ),
    ]
